version: '3.8'

services:
  # Qdrant vector database
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage:z
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
    restart: unless-stopped

  # Streamlit application
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: agentic-rag-app
    ports:
      - "8501:8501"
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads:z
    depends_on:
      - qdrant
    restart: unless-stopped


volumes:
  qdrant_storage: